networks:
  puc_mvp:
    driver: bridge 

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    hostname: mysql_host
    networks:
      - puc_mvp
    environment:
      MYSQL_ROOT_PASSWORD: 142536
      MYSQL_DATABASE: mvp2
      MYSQL_USER: app
      MYSQL_PASSWORD: app142536
    volumes:
      - mysql_data:/bitnami/mysql/data
      - ./mysql_container/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysql $$MYSQL_DATABASE -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1;'
      interval: 20s
      timeout: 5s
      retries: 10
  
  model:
    container_name: model_container
    hostname: model_host
    build: ./model_container
    depends_on:
      mysql:
        condition: service_completed_successfully
    networks:
      - puc_mvp
    ports:
      - "3001:3001"
    environment:
      APP_PORT: 3001
      DB_HOST: mysql_host
      DB_DATABASE: mvp2
      DB_USER: app
      DB_PASSWORD: app142536

  loader:
    container_name: loader_container
    hostname: loader_host
    build: ./loader_container
    networks:
      - puc_mvp

  api:
    container_name: api_container
    hostname: api_host
    build: ./api_container
    networks:
      - puc_mvp
    ports:
      - "3002:3002"
    environment:
      APP_PORT: 3002

  frontend:
    container_name: frontend_container
    hostname: frontend_host
    build: ./frontend_container
    networks:
      - puc_mvp
    ports:
      - "3003:3003"
    environment:
      APP_PORT: 3003

volumes:
  mysql_data: